### ISSUE TITLE
svcDebugActiveProcess always fail

### ISSUE THREAD

**Issue by 422404** [Stary2001/ScenicRoute#1]
Hello, here is my issue:
I'm using a modified version of this lib (n3ds kProcess offsets values changed to o3ds values, https://github.com/422404/ScenicRoute) and everytime I use proc_debug() function it give me an error with error code 0xf8c007f4 (Not implemented, Kernel, Not supported, Fatal).

PS: I only used proc_debug() on my process, don't know if that matter.

**Comment by Stary2001** [comment]
there is a global kernel flag that enables debugging - enable the dev unitinfo patch in Luma for now, until I can figure out how to patch it to always be on (requires at least some kernel11 RE.. )

On another note, you'll want to also call debug_enable() from debug.h to set the 'force debug' flag for your process, which allows you to debug any process.

**Comment by Stary2001** [comment]
Also, if you could PR your o3ds offset changes in the form of a function that sets the correct values depending on the current system, they would be much appreciated :)

**Comment by 422404** [comment]
I will try with luma3ds unitinfo patch as I already tried debug_enable().
I will make a function, it was only a quick fix :)

**Comment by Stary2001** [comment]
Thanks! for future reference i'm about in the usual places on irc (#3dsdev on efnet, #3dsdev/#cakey on freenode) most of the time if you would like to ask anything

**Comment by 422404** [comment]
Thank you :) I also done the PR but I think you've already been notified :^)

**Comment by 422404** [comment]
So now that I enabled the UNITINFO patch svcDebugActiveProcess freeze the console.
Code:
`ret = kproc_init();`
`printf("kproc_init returned: %08x\n", ret);`
`debug_enable();`
`printf("debug enabled\n");`
`pSelf = proc_open((u32)-1, FLAG_DEBUG);`

I tracked the lastest instruction that is executed with some printf() into proc_debug() function and it appear that on my side svcDebugActiveProcess hang the system.

**Comment by Stary2001** [comment]
Debugging a process freezes it as there are queued debug events (namely an attach event)... and you debug the current process (-1), meaning it gets frozen...

**Comment by 422404** [comment]
So now that I'm debugging Home menu it works, thanks ! :) And sorry for opening useless issues.

**Comment by Stary2001** [comment]
Not useless at all :) if you have any quick questions i'm on irc as always in #3dsdev on efnet/freenode. you can also PM me if you want.
